---
title: "Task1"
author: "Zofia Matiova"
date: "8/10/2024"
format:
  html:
    embed-resources: true
editor: source
---

## Question 1 title

Question description

```{r}
# code for solving task
v1 <- 18.12312321
v2 <- 29L
v3 <- "character variable Zofia Matiova" 
v4 <- TRUE
v5 <- 16 + 8i
print(c(v1, v2, v3, v4, v5))
```
## Question N title



```{r}
# code for solving task
```
## Question 2 title

Create the next vectors:
  * sequence from 5 to 75;
  * numbers: 3.14, 2.71, 0, 13;
  * with 100 `TRUE` values.
```{r}
# code for solving task
sequence_vector <- 5:75
number_vector <- c(3.14, 2.71, 0, 13)
true_vector <- rep(TRUE, 100)

sequence_vector
number_vector
true_vector
```

## Question 3 title

```{r}
# code for solving task
my_matrix <- matrix(c(12, 34, 87, -12.1, 0, 3.6, 0.5, 1.3, 8), nrow = 3, ncol = 3)
print(my_matrix)
```

## Question 4 title

```{r}
# code for solving task
char <- c("GGWP", "AFK")
numeric <- c(4.5, 5.5)
integer <- c(1350, 1L)
complex <- c(6+2i, 15+5i)
logical <- c(FALSE, TRUE)

my_list <- list(char, numeric, integer, complex, logical)

print(my_list)
```

## Question 5 title

```{r}
# code for solving task
age_factor <- factor(c("infant", "child", "adult"), levels = c("infant", "child", "adult"))
print(age_factor)
```

## Question 6 title

```{r}
# code for solving task
my_data <- data.frame(
  Name = c("John", "Anna", "Paul"),
  Age = c(25, 30, 35),
  Gender = c("Male", "Female", "Male"),
  Hight = c(195L, 171.3, 165.5)
)
  
  my_data_frame <- c("Student_Name", "Student_Age", "Student_Gender", "Student_Gender")
  print(my_data)
```

## Question 7 title

```{r}
# code for solving task
names(my_data) <- c("Meno", "Vek", "Pohlavie", "Výška")
my_data
```